image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test
  - coverage

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Default build cache settings to extend from
.build_cached:
  cache:
    key: "gradle-build"
    paths:
      # Only cache the gradle directory, as we do not use a shared cache
      - .gradle/
    policy: pull

build-order-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: build
  script:
    gradle order-microservice:assemble order-microservice:testClasses

checkStyle-order-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle order-microservice:checkstyleMain order-microservice:checkStyleTest
  allow_failure: false


PMD-order-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: staticAnalysis
  script:
    gradle order-microservice:pmdMain
  allow_failure: false

test-order-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: test
  script:
    - gradle order-microservice:test order-microservice:jacocoTestReport
    - cat order-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
  artifacts:
    when: always
    paths:
      - order-microservice/build/reports/jacoco/test/html/
      - order-microservice/build/reports/jacoco/test/jacocoTestReport.xml

coverage-order-microservice:
  extends:
    - .build_cached
  needs:
    - gradle_build
  dependencies:
    - gradle_build
  stage: coverage
  image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.9
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python /opt/cover2cover.py order-microservice/build/reports/jacoco/test/jacocoTestReport.xml $CI_PROJECT_DIR/order-microservice/src/main/java/ > order-microservice/build/reports/cobertura/cobertura.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: order-microservice/build/reports/cobertura/cobertura.xml